### ISSUE TITLE
help

### ISSUE THREAD

**Issue by d3oserek** [Qreaj/RiseAuthEmulator#3]
i cant click login button in rice

**Comment by ZadgeIsCool** [comment]
doesnt work with 6.0.13 only 6.0.12

**Comment by GhettoValorant** [comment]
mee two is not working

**Comment by GhettoValorant** [comment]
can you make a video
pls

**Comment by GhettoValorant** [comment]
emulator is not working is not opening

**Comment by d3oserek** [comment]
6.0.12 dont work

**Comment by Qreaj** [comment]
> emulator is not working is not opening

install java 8 and use java -jar command from command line and edit hosts file

**Comment by Qreaj** [comment]
> doesnt work with 6.0.13 only 6.0.12

because its for 6.0.12 not 6.0.13 lastest version emmulator will be realesed soon

**Comment by Qreaj** [comment]
> i cant click login button in rice

did you edit hosts file?
if yes ping auth.riseclient.com using cmd if ip is not 127.0.0.1 then its your windows issue

**Comment by Qreaj** [comment]
> doesnt work with 6.0.13 only 6.0.12

now its working download lastest release
